### ISSUE TITLE
Kotest configuration

### ISSUE THREAD

**Issue by nodh** [a-sit-plus/kmm-vc-library#19]
We had that error some months ago IIRC, that the XML file names for test results are too long (or contain invalid characters?).
Well, it happens again: https://github.com/a-sit-plus/kmm-vc-library/actions/runs/6048016515/job/16412582541#step:5:464

**Comment by JesusMcCloud** [comment]
Good news is: test names are not too long anymore.

Bad news is: it segfaults now

**Comment by JesusMcCloud** [comment]
#17 fixed this
