### ISSUE TITLE
DefaultCryptoService and SAN extensions

### ISSUE THREAD

**Issue by nodh** [a-sit-plus/kmm-vc-library#69]
Please reconsider adding the SAN extensions to the [JVM default implementation](https://github.com/a-sit-plus/kmm-vc-library/blob/develop/vclib/src/jvmMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt#L80) just for [one test](https://github.com/a-sit-plus/kmm-vc-library/blob/develop/vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopX509SanDnsTest.kt)

Also think about the [iOS implementation](https://github.com/a-sit-plus/kmm-vc-library/blob/develop/vclib/src/iosMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt), because the test for x509_san_dns in SIOP currently fails, see https://github.com/a-sit-plus/kmm-vc-library/actions/runs/9126951310/job/25096216868#step:5:496

**Comment by JesusMcCloud** [comment]
still relevant?

**Comment by nodh** [comment]
Fixed in https://github.com/a-sit-plus/kmm-vc-library/pull/70
